<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: seb
 * Date: Sat, 24 Jul 2021 02:46:47 +0200
 */
$conf['template'] = 'mindthedark';
$conf['license'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['userewrite'] = '2';
$conf['useslash'] = 1;
$conf['canonical'] = 1;
$conf['tpl']['mindthedark']['theme'] = 'dark';
