<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: Seb
 * Date: Sat, 24 Jul 2021 18:00:22 +0200
 */

$conf['title'] = 'Wiki';
$conf['license'] = '0';
$conf['disableactions'] = 'register';
$conf['proxy']['user'] = 'seb';
$conf['plugin']['cspheader']['defaultsrcValue'] = '\'self\' \'unsafe-inline\'';
$conf['plugin']['cspheader']['baseuriValue'] = '\'self\' \'unsafe-inline\'';
$conf['plugin']['inlinejs']['follow_htmlok'] = 0;
$conf['plugin']['cspheader']['enableHeader'] = '1';
$conf['plugin']['cspheader']['optionsInline'] = '1';
$conf['plugin']['cspheader']['optionsEval'] = '1';
