# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Sat, 24 Jul 2021 13:27:22 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated
